### ISSUE TITLE
Order precedence of resolving local profile name

### ISSUE THREAD

**Issue by vondeetzen** [hupe1980/cdk-multi-profile-plugin#2]
When working in a team currently every team member has to sync their local AWD profile names or the profile configuration has to be edited before running CDK.

A better approach could be some kind of precedence resolver. 

My suggestion for precedence would be:

1. Use `~/.cdkmultiprofileplung.json`
2. Use project local `package.json`for mapping

To not break back backward compatibility first the profile is looked up in `~/.cdkmultiprofileplung.json`. If no mapped account is found then the local `package.json` will be used for looking up a mapping.

As a result, there can be a team configuration in `package.json` and it can be overridden locally by every team member.

Currently I'm working this issue at https://github.com/vondeetzen/cdk-multi-profile-plugin

**Comment by hupe1980** [comment]
@vondeetzen  How about three stages?

1. homedir/.cdkmultiprofileplugin.json
https://nodejs.org/api/os.html#os_os_homedir
2. project dir/cdkmultiprofileplugin.json -> You can use it in combination with or without .gitignore
3. package.json -> the current solution

**Comment by vondeetzen** [comment]
> @vondeetzen How about three stages?
> 
>     1. homedir/.cdkmultiprofileplugin.json
>        https://nodejs.org/api/os.html#os_os_homedir
> 
>     2. project dir/cdkmultiprofileplugin.json -> You can use it in combination with or without .gitignore
> 
>     3. package.json -> the current solution

Sure. Already considered and as standalone mapper implemented a minute ago. Next is the precedence mapper and joining the results of mapping.

**Comment by hupe1980** [comment]
@vondeetzen Any updates?

**Comment by vondeetzen** [comment]
Trying to find some time within the next days. But still on this topic.
